### ISSUE TITLE
Honeypot script is never added to page

### ISSUE THREAD

**Issue by Ianvdl** [ulsdevteam/pkp-formHoneypot#2] opened 2018-11-07 06:48 UTC
Thank you for making this plugin available for others to use, I'm hoping that it will help cut down on the number of automated registrations we're seeing.

I followed the instructions:

- Downloaded the plugin to the generic directory
- Ran the upgrade script
- Configured the plugin in the journal manager

Everything appears to be fine - I don't see any errors in the apache logs - but the script is never added to the registration page. 

Our software versions are as follows:

OJS: 2.4.8.3 (also running ReCapcha v2 if that makes any difference)
PHP: 5.5.9
Apache: 2.4.7

The path to the registration page is: <hostname>/pub/user/register

Is there anything I'm missing that might prevent the plugin from adding the script template to the page?

Thanks for you time.

**Comment by ctgraham** [comment] 2019-01-29 18:34
@Ianvdl , sorry for just now seeing this issue.  Is this still a problem?  Do you have any additional info what might be the cause?

**Comment by Ianvdl** [comment] 2019-01-31 12:56
Hi @ctgraham 

Thanks for following up. I didn't actually manage to get the plugin working, we ended up using the "Stop Forum Spam" plugin for OJS 2 instead. It seems to have done the job so far.

My suspicion was that the Honeypot script didn't work because our URLs are rewritten, so the journals are all served at journal_path_subdomain.example.com/pub. This differs from the default example.com/index.php/journal_path. Maybe you have some insight into whether that may have been the problem?

I don't really have any other ideas why the field was never inserted into the form, there's no indication that anything actually goes wrong in the logs or otherwise.

**Comment by ctgraham** [comment] 2023-01-24 18:59
Closing this issue as outdated.

**Closed as completed by ctgraham** 2023-01-24 18:59 UTC
